# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab959db5bc6eaa8133d2efee31521639ac842eaeb47ca66fa9e3962c7c0c05d15bf8e50009cef877f8c8b99128096a28f16544d246287f79e7dfe0bc501abeed

test:
  secret_key_base: 4e90f264d4717d51ff9406b8e08661f82313732ccbafca5567005357d5a69df559d13222d46380d7f5c77684a5771ebf176bdc00b8e827450416ea53bf98da9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
